### ISSUE TITLE
openDSME

### ISSUE THREAD

**Issue by canace1224** [openDSME/openDSME#1]
I've been installing openDSMC, using OMNET++ version 5.1.1 When i compile the file example.ini it pops an error describing "library files for configuration"debug""is missing. Please help me solve this problem.
Besides that, it also shows Exception occurred executing command line.
Cannot run program "C:/Users/Canace" (in directory "C:\Users\Canace Ho\Downloads\inet-dsme-master\inet-dsme-master\simulations"): CreateProcess error=2, The system cannot find the file specified

**Comment by koalo** [comment]
The main problem is probably that you have spaces in your path (Canace Ho instead of e.g. Canace_Ho). Does that fix your problem?

**Comment by canace1224** [comment]
I don't think I have any space in my files path.

**Comment by koalo** [comment]
There is obviously a space: "C:\Users\Canace Ho\Downloads\inet-dsme-master\inet-dsme-master\simulations"

**Comment by canace1224** [comment]
[image: image.png]
it's only canace there actually.

**Comment by koalo** [comment]
Please use another directory (e.g. C:\myexperiments\)

**Comment by canace1224** [comment]
Means create a directory out from home file? How can I do that? Can provide
me some instructions? Appreciate your help

**Comment by koalo** [comment]
Sorry, I am not able to help you with basic file system operations. Please ask your supervisior!
